### ISSUE TITLE
Safari / WKWebView support

### ISSUE THREAD

**Issue by TheJKM** [kclyu/rpi-webrtc-streamer#25] opened 2018-01-23 20:24 UTC
Hi, is it possible to add support for Safari / WKWebView on iOS? Safari supports WebRTC since iOS 11 / macOS High Sierra, but this example (I tried /native-peerconnection) does not work. Support for Safari would be very nice, because there's no alternative on iOS and I'd like to use this piece of software because the low latency is very nice, especially for a Raspberry Pi.
I saw the fixed issue for iOS 11, but my problem is different. I get a Type error on line 108 of main_rws.js, this happens only on Safari.

**Comment by kclyu** [comment] 2018-01-24 05:06
I will make a plan to find a workaround to make it work on iOS/MacOS Chrome or Safari. 
But, I have spent a lot of time in other functions, so I do not have time to get into the cause of the problem yet, so I have been delaying the problem for a while. 

Advice and support are welcome if you have advice or have some troubleshooting.

If there is any progress in troubleshooting, I'll post it here.

**Comment by kclyu** [comment] 2018-01-31 08:18
I have committed the js/html files for this issue but it seems to work normally using the latest WebRTC native stack for normal operation. I will close the current issue after deb uploading.

**Closed as completed** 2018-02-01 05:20 UTC
